import Link from 'next/link'

import './global.css'

export const metadata = {
  title: {
    default: "Next.js tutorial",
    template: "%s | Guilherme"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <Link href={'/'}><h1>Header</h1></Link>
        </header>
        {children}
        <footer>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  )
}
